version: '3'
services:
  python_defaults: &python_defaults
    build:
      context: ./app
    volumes:
      - ./app:/app
      - ./.dev-local/home:/root
    working_dir: /app
    env_file:
      - ./.dev-local/home/.env

  py:
    <<: *python_defaults
    entrypoint: bash

  trade:
    <<: *python_defaults
    command: |
      --symbol=CAKE/USDT --size=3 --type=sell

